### ISSUE TITLE
Wordpress Integration Testing

### ISSUE THREAD

**Issue by UnderFenex** [gboone/gboone.github.io#18]
Hi Greg,

I was reading your post on WP Integration testing, it's very usefull :D.

Do you know a way to test under integration the get_query_var() function?

Thanks :)

**Comment by gboone** [comment]
Hoo! That takes me back, I haven't worked on WordPress in a while, been in Jekyll land for the last year and a half. I'm glad that post is still useful, though, thanks for reading. 

Again, I'm a little rusty but it looks like `get_query_var` is called from within the loop, so I think you'd want to simulate a pageload. I think there are ways to do that with the `factory` object. You might start with the [WP-CLI project's page](http://wp-cli.org/docs/plugin-unit-tests/) on plugin unit tests. I'm trying to find the documentation for the test suite itself but not turning up much. Good luck, and feel free to submit a PR back to this site if you end up finding a solution.
