### ISSUE TITLE
Pomodora

### ISSUE THREAD

**Issue by gallimorej** [gboone/gboone.github.io#3]
Seems like you've accidently fallen into using the pomodoro technique using each side of your record as an interval. I've found it works great for me -- been using it for maybe a year now.

http://en.m.wikipedia.org/wiki/Pomodoro_Technique

**Comment by gboone** [comment]
Thanks for the tip, Jeff. I've heard of Pomodoro and even tried using it once a while back. Always had a hard time actually taking a break at the end of the interval. I feel like I need a tool that will lock my screen or something to force me to take my eyes of my screen; timers are too easy to ignore. Any recommendations?

**Comment by gallimorej** [comment]
Greg--

Try this...

http://lifehacker.com/5982752/force-yourself-to-take-breaks-by-locking-yourself-out-of-your-computer-and-changing-the-keyboard-layout
________________________________

**Comment by gboone** [comment]
:+1: thanks, Jeff, I'll give it a shot! Hope all is well with you these days.
